name: pegsolitaire
description: Simple peg solitaire game

version: 0.4.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  quiver: ^3.2.1
  archive: ^3.4.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/hole.png
    - assets/unused.png
    - assets/english_board_winning_positions.txt
    - assets/peg_blue.png
    - assets/peg_blue_highlighted.png
    - assets/peg_grey.png
    - assets/peg_grey_highlighted.png
    - assets/peg_green.png
    - assets/peg_green_highlighted.png
    - assets/peg_red.png
    - assets/peg_red_highlighted.png
    - assets/peg_orange.png
    - assets/peg_orange_highlighted.png
    - assets/peg_yellow.png
    - assets/peg_yellow_highlighted.png